### ISSUE TITLE
Does not export items without authors

### ISSUE THREAD

**Issue by michaelewens** [melat0nin/zotero-roam-export#13] opened 2020-06-29 16:06 UTC
"Export to Roam" in the context menu results in no action for these types.  "Unreachable code after return statement" /loader.jm --> /bluebird/util.js

**Comment by melat0nin** [comment] 2020-07-02 13:34
Thanks for pointing this out, it's an important one (I rarely use webpage items so it's not something I've come across). Will investigate ASAP.

**Comment by melat0nin** [comment] 2020-07-04 20:44
@michaelewens can you show me the metadata of the item that's failing for you? I suspect it's because there's no author specified.

**Comment by richardlm** [comment] 2020-07-06 16:43
I know this isn't 'my' bug, but I can confirm that zotero-roam-export works when a web page snapshot has an author specified but it does nothing (no feedback, no error reported,...) when the author field is empty.
As web pages often do not have authors this is quite important.
I can supply the metadata for records if that helps.
Thanks.

**Comment by melat0nin** [comment] 2020-07-18 09:19
I think the problem is the lack of author rather than the item type, so I've changed the name of this issue. Working on it now.

**Comment by melat0nin** [comment] 2020-07-18 10:37
This should be fixed in [v1.10.1](https://github.com/melat0nin/zotero-roam-export/releases/tag/v1.10.1), let me know how you get on.

I've also added automatic updates, so no more manually re-installing 🚀

**Closed as completed by melat0nin** 2020-07-18 10:37 UTC
Labels: bug

**Comment by richardlm** [comment] 2020-07-18 14:55
Export of web pages (with no author / creator specified) works in this version.
Thanks.
